### PR TITLE
updated technology page copy and layout

### PR DESCRIPTION
**Pull request by moeamaya**

### CODE REVIEW

**Comment by chasballew** [comment]
@skylar - code review?

**Comment by sandersonet** [comment]
Great work @moeamaya  -- My only critique here is that much of the new copy is embedded directly into HTML.  I think it would be helpful if we kept all copy in the front matter, so non-technical users can stay out of the weeds when making simple copy edits.  Other than that, very very nice work!

**Comment by moeamaya** [comment]
Thanks Skylar!

Sorry I'm not quite sure I understand, do you mind clarifying. I tried to keep all the copy up in the Markdown or Yaml up top and used handlebars template strings to refer to that copy.

**Comment by moeamaya** [comment]
@sandersonet nvm double checking I see what you mean. I'll fix that up and push up

**Comment by sandersonet** [comment]
Thanks for the quick fix.  Merge at will @moeamaya

**Pull request merged**
